kind: Service
apiVersion: v1
metadata:
  name: hello
  namespace: default
  labels:
    app: hello
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: hello
  type: NodePort