version: '3'
services:
  app:
    image: ccchieh/uwsgi-flask
    container_name: app
    volumes:
      - "./main.py:/root/app/main.py"
  nginx:
    image: nginx:1.19
    container_name: nginx
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "5004:80"